= API Visualizer Architecture Visualization


The Architecture visualization shows the topology of your application network. Use it to document and share your network structure without exposing metrics. You can change display names, add tags, and assign nodes to layers directly in the canvas.

== View Information About One Service in Your Network

When you select a node within the canvas, the node and its dependency stack are highlighted and all unconnected nodes are unavailable.
API Visualizer displays information about the node in a card. This card is divided into the following tabs:

* *Details*
Provides information about the node.
* *Customization*
Provides information about the layer to which the node is assigned and the tags assigned to the node. You can xref:customize-your-canvas.adoc#display-name[edit the node's display name] or xref:layers.adoc#set-a-layer-ui[change the layer] and xref:use-tags-in-visualizer.adoc#set-tag-ui[tags] from this section.

== Filter Your View

When you select a node (service) that has dependents and dependencies, you have the option to also select all nodes related to the service you selected. If the node you select does not have dependents and dependencies, this option is not offered.

You can hide nodes through what you select in the canvas:

* To hide a single node, select it, and then click *Hide selected service*.
* To hide multiple nodes, multiselect them, and then click *Hide selected services*.
* To hide all of the services other than the selected nodes, click *Hide other services*.
If you want to hide everything that is not related to a given dependency stack, select a node and then click *Select dependents and dependencies*, which selects all nodes related to the service which you selected. Then, click *Hide other services*.

You can search for a node (service) in the *Search services* text field. Services containing your search in any part of their name are highlighted, while others fade.

[[export-view]]
== Export Your Network View

You can export the view of your network showing on your canvas to a PNG file by clicking the *Export as Image* button next to the zoom controls in the bottom right.

If you customized your view, the customized network topology is exported.


== See More

* xref:view.adoc[]
* xref:use-tags-in-visualizer.adoc[]
* xref:layers.adoc[]
