= CloudHub Setup
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Verify Supported CloudHub Mule Runtime Engine (Mule) Versions

Anypoint Visualizer only includes activity from applications deployed to a supported version of Mule runtime engine (Mule). When deploying a Mule app or API, you must ensure that you are using a supported version of Mule as the deployment target.
Anypoint Visualizer supports the following Mule versions running on CloudHub:

* Mule version 3.8.7
* Mule version 3.9.x
* Mule version 4.1.x
* Mule version 4.2.x

[NOTE]
If your version of Mule was released before June 30th 2018, to ensure you have the correct Anypoint Visualizer agent, upgrade your version of Mule to any of the supported versions listed in this section. You can do this update with zero downtime for CloudHub applications, APIs, and proxies.
These versions are listed in Runtime Manager > Runtime Version. Expand the Show old patch releases section in the runtime versions drop-down.

== Verify Supported Mule Runtime Engine (Mule) Versions for Metrics

The metrics that Anypoint Visualizer displays come from Anypoint Monitoring. As a result, metrics are shown in Anypoint Visualizer only for applications running on Mule versions that are also supported for Anypoint Monitoring:

* Mule 3.8.7 patch releases available on August 14, 2019 or later.
* Mule 3.9.x patch releases available on April 5, 2019 or later.
* Mule 4.1.x patch releases available on March 22, 2019 or later.
* Mule 4.2.x.

To see your app, its connections, and the related metrics in Anypoint Visualizer, enable the Anypoint Monitoring agent after you upgrade.

[NOTE]
If you currently have Anypoint Monitoring enabled for applications running on 3.9.x-AM or 4.x-AM, app-level monitoring continues to work for those apps.
However, metrics at the connection level do not appear.
Update your applications to run on non-AM Mule versions (3.9.x and 4.x) for better functionality and the latest patch updates as soon as they are available.

== Enable the Monitoring Agent

In order for your app to appear in Anypoint Visualizer and for metrics to be displayed, you must manually enable the Anypoint Monitoring agent for the following Mule versions:

* Mule Version 3.8.7 patch releases available after August 14, 2019
* Mule Version 3.9 patch releases available after April 5, 2019
* Mule Version 4.1 patch releases available after March 22, 2019
* Mule Version 4.2

To enable the Anypoint Monitoring agent:

. Verify that you are a user with Anypoint Monitoring User permission.
. Sign in to Anypoint Platform and click *Anypoint Monitoring*.
. Click *Settings*.
. Select *CloudHub*.
. From the *Environment* drop-down list, choose an environment.
. In *List of resources in <Environment Name>*, search for an app to visualize.
. Next to the app, click *Enable & Apply* to enable visualization and monitoring for the app.

For more information about Anypoint Monitoring, see xref:monitoring::enable-apps-deployed-to-cloud.adoc[Enable Monitoring Using the UI].

== Verify Supported Mule Versions for Policies

The APIs and policies that Anypoint Visualizer displays in the Policy visualization come from an update to the agent in Mule runtime engine (Mule). As a result, Anypoint Visualizer shows policies only for apps running on supported Mule versions released on December 12, 2019 or later.

== Dedicated Load Balancers

Anypoint Visualizer supports dedicated load balancers for CloudHub apps using Mule version 3.9.x (version released April 5, 2019 or later).

[NOTE]
Anypoint Visualizer cannot correctly resolve dedicated load balancer connections for CloudHub apps using Mule 4 runtime versions at this time.

== Manage Performance and Data Collection

The agent that Anypoint Visualizer uses to collect metadata sometimes has a performance impact.

For more information about data collection and performance, see xref:visualizer::technical.adoc[Manage Performance and Data Collection].
