= CloudHub Setup in API Visualizer


API Visualizer only includes activity from applications deployed to a supported version of Mule runtime engine (Mule). When deploying a Mule app or API, make sure that you are using a supported version of Mule as the deployment target.

[NOTE]
If your version of Mule was released before June 30th 2018, to ensure you have the correct API Visualizer agent, upgrade your version of Mule to any of the supported versions listed in this section. You can do this update with zero downtime for CloudHub applications, APIs, and proxies.
These versions are listed in Runtime Manager > Runtime Version. Expand the Show old patch releases section in the runtime versions drop-down.

== Verify Supported Mule Runtime Engine (Mule) Versions for Metrics

The metrics that API Visualizer displays come from Anypoint Monitoring. As a result, metrics are shown in API Visualizer only for applications running on Mule versions that are also supported for Anypoint Monitoring.

To see your app, its connections, and the related metrics in API Visualizer, enable the Anypoint Monitoring agent after you upgrade.

[NOTE]
If you currently have Anypoint Monitoring enabled for applications running on 4.x-AM, app-level monitoring continues to work for those apps.
However, metrics at the connection level do not appear.
Update your applications to run on non-AM Mule versions for better functionality and the latest patch updates as soon as they are available.

== Enable the Monitoring Agent

In order for your app to appear in API Visualizer and for metrics to be displayed, manually enable the Anypoint Monitoring agent for the following Mule versions:

* Mule Version 4.1 patch releases available after March 22, 2019
* Mule Version 4.2

To enable the Anypoint Monitoring agent:

. Log in to Anypoint Platform using an account that has the Anypoint Monitoring User permission. 
. In the navigation bar or the main Anypoint Platform screen, click *Monitoring*.
. In the Anypoint Monitoring navigation menu, click *Settings*.
. Select *CloudHub*.
. From the *Environment* drop-down list, choose an environment.
. In *List of resources in <Environment Name>*, search for an app to visualize.
. Next to the app, click *Enable & Apply* to enable visualization and monitoring for the app.

For more information about Anypoint Monitoring, see xref:monitoring::enable-apps-deployed-to-cloud.adoc[Enable Monitoring Using the UI].

== Verify Supported Mule Versions for Policies

The APIs and policies that API Visualizer displays in the Policy visualization come from an update to the agent in Mule runtime engine (Mule). As a result, API Visualizer shows policies only for apps running on supported Mule versions released on December 12, 2019 or later.

== Manage Performance and Data Collection

The agent that API Visualizer uses to collect metadata sometimes has a performance impact.

For more information about data collection and performance, see xref:visualizer::manage-performance.adoc[Manage Performance and Data Collection].
