= Customize the Canvas
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


You can choose what appears in your Visualizer canvas by applying filters for environments, tags, and services.
This enables you to hide the nodes that you do not want to see in the application graph.
Filters have a cascading design, so all nodes that don't belong to the checked environments or tags are automatically hidden from the list of services.

You can toggle *Show dependents and dependencies* to see the services and dependencies of the nodes and services which have the selected tags.
The *View* card and the canvas are updated to display the current selection.

Visualizer editors can save defined views so that any Visualizer user can access them.
When you close Anypoint Visualizer and reload the canvas later, the views you last accessed are displayed.
You can use all unicode characters with UTF-8 encoding (such as international letters, symbols, and numbers) to customize Layers, Tags, and Display Names in the Visualizer UI or by using a runtime property.

Anypoint Visualizer supports all unicode characters with UTF-8 encoding, including international characters, when you set layer names, tag names, and display names, whether you set them in the UI or using a runtime property.


== Layers

You can use one of the default layers provided by Anypoint Visualizer, or add a custom layer to create a visual representation of the apps in your network.

To automate the classification of nodes into layers, configure the property `anypoint.platform.visualizer.layer=<name>`.

For more information, see xref:layers.adoc[Use Layers in Anypoint Visualizer].

== Tags

You can add tags to API, application, proxy, or other services, so you can use the tags as filters to adjust your view.

To automate adding tag(s) to a node, use the property `anypoint.platform.visualizer.tags=<name>, <name>`.

For more information, see xref:use-tags-in-visualizer.adoc[Use Tags in Visualizer].

== Display Name

You can edit the display name of an API, application, or other service to provide a more readable, explanatory title.

To automate adding a display name to the node, configure the property `anypoint.platform.visualizer.displayName=<name>`.

== Views

Visualizer editors define views based on filtered environments and tags. These defined views are auto discoverable and available to all Visualizer users who have permission for the included environments.

For more information, see xref:view.adoc[Visualizer Views]
