= Manage Performance and Data Collection
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: technical.adoc

Anypoint Visualizer collects runtime information from running applications, APIs, and proxies to detect all of its dependencies. The information collected includes IP address and URL (without parameters) of the incoming request, as well as URL (without parameters), and some header values of outgoing requests. This information is encrypted and stored in a database.

[%header%autowidth.spread]
|===
| Metadata | Description
| node_info | General information about the node.
| org_id | The organization where the node is deployed.
| ip | The IP address of the node.
| type | Specifies whether the node is an API or Mule application.
| deployment_id | An internal ID that specifies the hash of the application or API.
| app_name | The name of the application.
| url | The fully qualified domain of the application.
|===

The agent that Anypoint Visualizer uses to collect metadata may have a performance impact.

== Reduce Potential Performance Impact for CloudHub

To reduce any potential performance impact for an application running in CloudHub, you can disable data collection and the Anypoint Monitoring agent.

=== Disable Data Collection in CloudHub

If you are using the following Mule versions, you can disable data collection by setting an application property:

* Mule Version 4 Released Before March 22, 2019
* Mule Version 3.9 Released Before April 5, 2019

. Set the application property `anypoint.platform.config.visualizer.agent.enabled=false`.
. Redeploy the application.

=== Disable the Anypoint Monitoring agent in CloudHub

If you are using the following Mule versions, you can disable the Anypoint Monitoring agent:

* Mule Version 4 Released on March 22, 2019 or Later
* Mule Version 3.9 Released on April 5, 2019 or Later
* Mule Version 3.8.7 Released on August 14, 2019 or Later

include::partial$include-nav-steps-AM-user-permission.adoc[]

. Click *Settings*.
. Select *CloudHub*.
. From the *Environment* drop-down list, choose an environment.
. In *List of resources in <Environment Name>*, search for an application whose metrics you wish to see.
. Next to application, click *Disable & Apply* to disable monitoring for the application.

== Reduce Potential Performance Impact for Standalone Mule

Anypoint Visualizer requires an additional header injection to work for standalone Mule deployments.

To disable the additional header injection, set the following property:

----
anypoint.platform.config.analytics.agent.header_injection.disabled=true
----

Additionally, to reduce potential performance impact for applications running in a standalone instance of Mule, you can do one of the following:

* Deploy the application to a server without the Anypoint Monitoring agent installed.
* Disable data collection for a specific server.
To disable data collection for a server and all the applications deployed to that server, set the following property at the server level (not the application level):
+
----
anypoint.platform.config.analytics.agent.disabled=true
----

[NOTE]
This disables monitoring for applications on the server as well.

== Reduce Potential Performance Impact for Runtime Fabric

Anypoint Visualizer requires an additional header injection to work for Runtime Fabric deployments.

To disable the additional header injection, set the following property:

----
anypoint.platform.config.analytics.agent.header_injection.disabled=true
----
