= Set up Anypoint Visualizer
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Configure the roles and permissions required to use Anypoint Visualizer and understand what to consider when deploying applications.

== Configure Permissions

To access Anypoint Visualizer, you must be assigned a role that has one of the following permissions:

* *Runtime Manager > Read Applications* 
Enables a user to view the graph of an app network, but does not allow them to make changes.
* *API Manager > View Policies or Manage Policies*
Enables a user to view the APIs linked to their Mule applications and the policies applied to those APIs. Only relevant for the Policy Visualization.
* *Visualizer > Visualizer Editor* 
Enables a user to view and modify the graph of an app network. 
You can create a xref:access-management::roles.adoc#custom-roles[custom role] and assign the *Visualizer Editor* permission to it.
[NOTE]
The *Visualizer Editor* permission can only be assigned within the master organization.

== Select a Deployment Type

Anypoint Visualizer supports the following deployment types:

* xref:visualizer::cloudhub-setup.adoc[CloudHub]
* xref:visualizer::standalone-mule-setup.adoc[Standalone Mule]
* xref:visualizer::runtime-fabric-setup.adoc[Runtime Fabric]

== Deploy an App

When you deploy an app you want to view in Anypoint Visualizer, ensure that you select a supported version of Mule as the deployment target. See xref:runtime-manager::index.adoc[Runtime Manager] for more information.

After redeploying an app, all metadata collected by Anypoint Visualizer is removed for that app. The number of inbound connections for the app node is reset.

== Verify Supported Connectors

Anypoint Visualizer can monitor activity for outbound connections on specific connectors.

For Mule version 3.9.x, the following connectors are supported:

* Salesforce
* HTTP/HTTPS
* Database
* All connectors based on the Connector DevKit

For Mule version 4.1.x, the following connectors are supported:

* Salesforce
* HTTP/HTTPS
* Database
* Mule 4 Extension Connectors


=== Manage Performance and Data Collection

The agent that Anypoint Visualizer uses to collect metadata sometimes has a performance impact.

For more information about data collection and performance, see xref:visualizer::technical.adoc[Manage Performance and Data Collection].
