= Set up Anypoint Visualizer
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Configure the roles and permissions required to use Anypoint Visualizer and understand what to consider when deploying applications.

== Configure Permissions

To access Anypoint Visualizer, you must be assigned a role that has one of the following permissions:

* *Runtime Manager > Read Applications*: Enables a user to view the graph of an application network, but does not allow them to make changes.
* *Visualizer > Visualizer Editor*: Enables a user to view and modify the graph of an application network. +
You can create a xref:access-management::roles.adoc#custom-roles[custom role] and assign the *Visualizer Editor* permission to it.
[NOTE]
The *Visualizer Editor* permission can only be assigned within the master organization.

== Set Up for CloudHub

=== Verify Supported CloudHub Mule Runtime Engine (Mule) Versions

Anypoint Visualizer only includes activity from applications deployed to a supported version of Mule runtime engine (Mule). When deploying a Mule application or API, you must ensure that you are using a supported version of Mule as the deployment target.

Anypoint Visualizer supports the following Mule versions running on CloudHub:

* Mule version 3.9.x
* Mule version 3.9.1-AM
* Mule version 4.1.x
* Mule version 4.1.x-AM

[NOTE]
If your version of Mule was released before June 30th 2018, to ensure you have the correct Visualizer agent, upgrade your version of Mule to any of the supported versions listed in this section. You can do this update with zero downtime for CloudHub applications, APIs, and proxies.

These versions are listed in *Runtime Manager > Runtime Version*. Expand the *Show old patch releases* section in the runtime versions drop-down.

=== Verify Supported Mule Runtime Engine (Mule) Versions for Metrics

The metrics that Visualizer displays come from Anypoint Monitoring. As a result, metrics are only shown in Visualizer for applications running on these Mule versions:

* Mule 3.9.1-AM
* Mule 4.1.x.-AM
* Mule 3.9.x patch releases available on April 5, 2019 or later. To see your application and the related metrics in Visualizer, you must also enable the Monitoring agent after you upgrade as described in the next section. 
* Mule 4.1.x patch releases available on March 22, 2019 or later. To see your application and the related metrics in Visualizer, you must also enable the Monitoring agent after you upgrade as described in the next section.

=== Enable the Monitoring Agent for Mule Version 4.1 Upgrades After March 22, 2019, or Mule Version 3.9 Upgrades After April 5, 2019

If you upgrade to Mule version 3.9.x (released April 5, 2019 or later) or 4.1.x (released March 22, 2019 or later), you must enable the Anypoint Monitoring agent in order for your application to appear in Visualizer, and for metrics to be displayed.

To enable the Anypoint Monitoring agent:

. Verify that you are a user with *Anypoint Monitoring User* permission.
. Sign in to Anypoint Platform and click *Anypoint Monitoring*.
. Click *Settings*.
. Select *CloudHub*.
. From the *Environment* drop-down list, choose an environment.
. In *List of resources in <Environment Name>*, search for an application to visualize.
. Next to the application, click *Enable & Apply* to enable visualization and monitoring for the application.

For more information about Anypoint Monitoring, see xref:monitoring::enable-apps-deployed-to-cloud.adoc[Enable Monitoring Using the UI].

== Set up for Standalone Mule 

=== Supported Standalone Mule and Runtime Fabric Mule Versions

Anypoint Visualizer supports the following Mule versions for standalone Mule and Runtime Fabric deployments:

* Mule Runtime, version 3.8.7
* Mule Runtime, version 3.9.1+
* Mule Runtime, version 4.1.1+ +
[NOTE]
By default, Visualizer is disabled for Mule 4. See <<enable_header_injection,enable the header injection>> for more information. 

=== Standalone Mule Setup

To support Visualizer for standalone Mule deployments, xref:monitoring::am-installing.adoc[install the Anypoint Monitoring agent]. 

=== Runtime Fabric Setup

Follow the instructions for xref:1.2@runtime-fabric::install-create-rtf-arm.adoc[setting up Runtime Fabric]. After you install Runtime Fabric, Visualizer can display applications that are running and deployed to Runtime Fabric.

Visualizer relies on a header injection to display connections between services correctly. The header injection is disabled by default for Mule 4. The correct connections will not be displayed for your Mule 4 Runtime Fabric applications unless you <<enable_header_injection,enable the header injection>>. 

Known Limitations:

* If a CloudHub application with the old Visualizer agent is calling a Runtime Fabric ingress endpoint, you see an extra edge from the CloudHub application to a node with the IP for the controller.
* If a Mule application deployed to Runtime Fabric is calling a Mule application deployed to CloudHub using its DNS, the correct connection will be on the Visualizer canvas, but there will be an additional edge from the External Traffic node to the CloudHub application.


[enable_header_injection]
=== Enable Header Injection

Visualizer requires an additional header injection to work properly for standalone Mule and Runtime Fabric deployments.
However, due to a potential performance impact for Mule 4.1.x, header injection is disabled by default.

[NOTE]
For Runtime Fabric, you must enable the inject header at the application level, while for a standalone Mule deployment, you must enable the header injection at the server, not application, level.

Set the following property in the server's properties:

----
anypoint.platform.config.analytics.agent.header_injection.disabled=false
----

[NOTE]
You must set the property to `false` as shown in the example to enable header injection, since the property is `disabled`.

For standalone Mule deployments, all applications running on the server are affected by this setting.

== Verify Supported Connectors

Anypoint Visualizer can monitor activity for outbound connections on specific connectors.

For Mule version 3.9.x, the following connectors are supported:

* Salesforce
* HTTP/HTTPS
* Database
* All connectors based on the Connector DevKit

For Mule version 4.1.x, the following connectors are supported:

* Salesforce
* HTTP/HTTPS
* Database
* Mule 4 Extension Connectors

== Dedicated Load Balancers

Visualizer supports dedicated load balancers for apps using Mule version 3.9.x (version released April 5, 2019 or later).

== Deploy an Application

When you deploy an application you want to view in Anypoint Visualizer, ensure that you select a supported version of Mule as the deployment target. See xref:runtime-manager::index.adoc[Runtime Manager] for more information.

After redeploying an application, all metadata collected by Anypoint Visualizer is removed for that application. The number of inbound connections for the application node is reset.

== Disable Data Collection

The agent that Anypoint Visualizer uses to collect metadata may affect performance. 

To reduce any potential performance impact for an application running in CloudHub you can disable data collection.

=== Mule version 4 released before March 22, 2019 or Mule Version 3.9 Released Before April 5, 2019

To reduce any potential impact on performance for an application running in CloudHub:

. Set the application property `anypoint.platform.config.visualizer.agent.enabled=false`.
. Redeploy the application.

=== Mule Version 4 Released on March 22, 2019 or Later, or Mule Version 3.9 Released on April 5, 2019 or Later

To reduce the monitoring impact on performance for an application running in CloudHub, disable the Monitoring agent:

. Verify that you are a user with *Anypoint Monitoring User* permission.
. Sign in to Anypoint Platform and click *Anypoint Monitoring*.
. Click *Settings*.
. Select *CloudHub*.
. From the *Environment* drop-down list, choose an environment.
. In *List of resources in <Environment Name>*, search for an application whose metrics you wish to see.
. Next to application, click *Disable & Apply* to disable monitoring for the application.

=== Manage Performance for Standalone Mule

Reducing performance impact for an application running in a standalone Mule is done at the server level. You can do one of the following:

* Deploy the application to a server that doesn't have the Anypoint Monitoring agent installed.
* Disable data collection for a specific server. To disable data collection for a server and all the applications deployed to that server, set the following property at the server level:
+
----
anypoint.platform.config.analytics.agent.disabled=true 
----
+
[NOTE]
This property disables monitoring for applications on the server as well.
