= Set up Anypoint Visualizer
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Configure the roles and permissions required to use Anypoint Visualizer and understand what to consider when deploying applications.

== Configure Permissions

To access Anypoint Visualizer, you must be assigned a role that has one of the following permissions:

* *Runtime Manager > Read Applications*: Enables a user to view the graph of an application network, but does not allow them to make changes.
* *Visualizer > Visualizer Editor*: Enables a user to view and modify the graph of an application network. +
You can create a xref:access-management::roles.adoc#custom-roles[custom role] and assign the *Visualizer Editor* permission to it.
[NOTE]
The *Visualizer Editor* permission can only be assigned within the master organization.

== Set Up for CloudHub

=== Verify Supported CloudHub Mule Runtime Engine (Mule) Versions

Anypoint Visualizer only includes activity from applications deployed to a supported version of Mule runtime engine (Mule). When deploying a Mule application or API, you must ensure that you are using a supported version of Mule as the deployment target.

Anypoint Visualizer supports the following Mule versions running on CloudHub:

* Mule version 3.9.1+
* Mule version 3.9.1-AM
* Mule version 4.1.x
* Mule version 4.1.x-AM

[NOTE]
If your version of Mule was released before June 30th 2018, to ensure you have the correct Visualizer agent, upgrade your version of Mule to any of the supported versions listed in this section. You can do this update with zero downtime for CloudHub applications, APIs, and proxies.

These versions are listed in *Runtime Manager > Runtime Version*. Expand the *Show old patch releases* section in the runtime versions drop-down.

=== Verify Supported Mule Runtime Engine (Mule) Versions for Metrics

The metrics that Visualizer displays come from Anypoint Monitoring. As a result, metrics are only shown in Visualizer for applications running on these Mule versions:

* Mule 3.9.1-AM
* Mule 4.1.x.-AM
* Mule 4.1.x patch releases available after March 23, 2019. To see your app and the related metrics in Visualizer, you must also enable the Monitoring agent after you upgrade as described in the next section.

=== Enable the Monitoring Agent for Mule Version 4.1.x Upgrades After March 23, 2019

If you upgrade to Mule version 4.1.x released after March 23, 2019, you must enable the Anypoint Monitoring agent in order for your application appear in Visualizer and for metrics to be displayed.

To enable the Anypoint Monitoring agent:

. Verify that you are a user with *Anypiont Monitoring User* permission.
. Sign in to Anypoint Platform and click *Anypoint Monitoring*.
. Click *Settings*.
. Select *CloudHub*.
. From the *Environment* drop-down list, choose an environment.
. In *List of resources in <Environment Name>*, search for an application you wish to visualize.
. Next to application, click *Enable & Apply* to enable visualization and monitoring for the application.

For more information about Anypint Monitoring, see xref:monitoring::monitoring:enable-apps-deployed-to-cloud.adoc[Enable Monitoring Using the UI].

== Set up for Standalone Mule 

=== Verify Supported Standalone Mule Runtime Engine (Mule) Versions

Anypoint Visualizer supports the following Mule versions for standalone Mule deployments:

* Mule Runtime, version 3.8.5+
* Mule Runtime, version 3.9.1+
* Mule Runtime, version 4.1.1+

=== Standalone Mule Setup

To support Visualizer for standalone Mule deployments, xref:monitoring::am-installing.adoc[install the Anypoint Monitoring agent]. 

== Verify Supported Connectors

Anypoint Visualizer can monitor activity for outbound connections on specific connectors.

For Mule version 3.9.x, the following connectors are supported:

* Salesforce
* HTTP/HTTPS
* Database
* All connectors based on the Connector DevKit

For Mule version 4.1.x, the following connectors are supported:

* Salesforce
* HTTP/HTTPS
* Database
* Mule 4 Extension Connectors

== Deploy an Application

When you deploy an application you want to view in Anypoint Visualizer, ensure that you select a supported version of Mule as the deployment target. See xref:runtime-manager::index.adoc[Runtime Manager] for more information.

After redeploying an application, all metadata collected by Anypoint Visualizer is removed for that application. The number of inbound connections for the application node is reset.

== Disable Data Collection

The agent that Anypoint Visualizer uses to collect metadata may affect performance. 

To reduce any potential performance impact for an application running in CloudHub you can disable data collection.

=== Disable Data Collection for Mule version 4 released before March 23, 2019

To reduce any potential impact on performance for an application running in CloudHub:

. Set the application property `anypoint.platform.config.visualizer.agent.enabled=false`.
. Redeploy the application.

=== Disable Data Collection for Mule version 4 released after March 23, 2019

To reduce the monitoring impact on performance for an application running in CloudHub, disable the Monitoring agent:

. Verify that you are a user with *Anypiont Monitoring User* permission.
. Sign in to Anypoint Platform and click *Anypoint Monitoring*.
. Click *Settings*.
. Select *CloudHub*.
. From the *Environment* drop-down list, choose an environment.
. In *List of resources in <Environment Name>*, search for an application whose metrics you wish to see.
. Next to application, click *Disable & Apply* to disable monitoring for the application.

=== Manage Performance for Standalone Mule

Reducing performance impact for an application running in a standalone Mule is done at the server level. You can do one of the following:

* Deploy the application to a server that doesn't have the Anypoint Monitoring agent installed.
* Disable data collection for a specific server. To disable data collection for a server and all the applications deployed to that server, set the following property at the server level:
+
----
anypoint.platform.config.analytics.agent.disabled=true 
----
+
[NOTE]
This property disables monitoring for applications on the server as well.
+
To disable the header injection for an application, set the following application property and redeploy the application:
+
----
anypoint.platform.config.analytics.agent.header_injection.disabled=true 
----

