= Standalone Mule Setup
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Supported Standalone Mule

Anypoint Visualizer supports the following Mule versions for standalone Mule deployments:

* Mule 3.8.7
* Mule 3.9.1+
* Mule 4.1.x
* Mule 4.2.x

== Install Agent

To support Anypoint Visualizer for standalone Mule deployments, install the xref:monitoring::am-install.adoc[Anypoint Monitoring agent].

== Enable Header Injection

Visualizer requires an additional header injection for standalone Mule deployments.
However, due to a potential performance impact for Mule 4, header injection is disabled by default.
For a standalone Mule deployment, you must enable the header injection at the server (not app) level.
This affects all applications running on the server.

. To enable the header injections for apps deployed to a standalone Mule, click *Server* in the menu on the left of *Runtime Manager*.
. Select the server for which to enable the header injection, and click *Manage Server*.
. Click the Properties tab, and set the following property in the server:
`anypoint.platform.config.analytics.agent.header_injection.disabled=false`.
You must set the property to `false` as shown in the example to enable header injection, since the property is disabled by default.

== Manage Performance for Standalone Mule

The agent that Anypoint Visualizer uses to collect metadata may affect performance.
To reduce any potential performance impact for an app running in standalone Mule, you can disable data collection.

Reduce performance impact for an app running in a standalone Mule at the server level. You can do one of the following:

* Deploy the app to a server that doesn’t have the Anypoint Monitoring agent installed.
* Disable data collection for a specific server and all the applications deployed to that server by setting the following property at the server level:
`anypoint.platform.config.analytics.agent.disabled=true`.
This property disables monitoring for applications on the server as well.
