= Standalone Mule Setup
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Verify Supported Standalone Mule Versions

Anypoint Visualizer supports the following Mule versions for standalone Mule deployments:

* Mule 3.8.7
* Mule 3.9.x
* Mule 4.1.x
* Mule 4.2.x

== Install Agent

To support Anypoint Visualizer for standalone Mule deployments, install the xref:monitoring::am-installing.adoc[Anypoint Monitoring agent].

[NOTE]
The APIs and policies that Anypoint Visualizer displays in the Policy visualization come from an update to the agent. As a result, policies are shown in Anypoint Visualizer only if your deployments use an agent from December 19, 2019 or later.

== Enable Header Injection

Anypoint Visualizer requires header injection for standalone Mule deployments so that the deployments display the correct connections.
However, due to a potential performance impact, header injection is disabled by default for Mule version 4.x with Anypoint Monitoring agent released before <insert UA 2.2.2 hybrid release date>. You must enable header injection at the server (not app) level.
This affects all applications running on the server.

. To enable header injection for apps deployed to a standalone Mule instance, click *Server* in the menu on the left of *Runtime Manager*.
. Select the server for which to enable header injection and click *Manage Server*.
. Click the Properties tab and set the following property in the server:
`anypoint.platform.config.analytics.agent.header_injection.disabled=false`
You must set the property to `false`, as shown in the example to enable header injection, because the property is disabled by default.

Additionally, you must use version 1.5.12 or higher of the HTTP connector in your Mule 4 applications.
=== Manage Performance and Data Collection

The agent that Anypoint Visualizer uses to collect metadata sometimes has a performance impact.

For more information about data collection and performance, see xref:visualizer::technical.adoc[Manage Performance and Data Collection].
