= Views
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Visualizer views enable you to create and save private views and views that you can share with others who have access to the environment that contains the shared views. 

== Private View

Each Visualizer user has a private view. When you access Visualizer the first time, your private view is displayed. Each subsequent time you access Visualizer, your private view reflects the view you last accessed and saved. 

Views that you have accessed recently appear under *Recent Items* in the top navigation bar. 

In your private view, you can:

* Edit and save
* Rename
* Discard changes
* Export the view as a PNG

You can't delete or share a private view. 

You can modify public (shared) views, but you can't save the changes you make. 

== Shared Views

Shared views are created and shared (made public) by users with the *Visualizer Editor* permission. Anyone who has permission for the environment can see shared views, but only editors can create, rename, and edit public views. 

It is useful to share views in cases where you want to share the app network graph with team members so they can use it to plan work, study the architecture of the app network, and troubleshoot more easily.

== Create a View

== Edit a View

Rename...

== Share a View

== Delete a View




