= Visualizer Application Network
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Use Anypoint Visualizer to view a graph of your application network.

Anypoint Visualizer automatically generates the topology of the application.
To maximize visualization readability, consumer nodes (nodes that only have outbound connections) are shown at the top. All backend systems are also shown.

When the ClientId is detected for a consumer node, the nodes are grouped by ClientId; otherwise, it is grouped under the External Traffic node. For the ClientId to be detected, the target application, API, or proxy should have the Client Id enforcement policy. For usability purposes, Client App names replace ClientIds in canvas. All Client Apps that call the same mule app are grouped into a single Client App group node. The number of Client Apps in the group are specified in the display name.

When viewing or modifying a graph, Anypoint Visualizer provides the following functionality:

* Zoom control: Use the zoom in, zoom out, and zoom fit buttons on the bottom right corner of the canvas to control the zoom. You can also use scroll to zoom in and out.
* Pan the visualization: Click and drag on the canvas to pan the visualization.

== View an Application Network in an Organization

. From Management Center, select *Visualizer*.
+
If Visualizer is not available, contact your system administrator to ensure that you have the correct permissions to access the application.

. In the environment filters in the *View* card, select an environment.
+
Anypoint Visualizer displays only the environments you have permissions to view.

. Click the check box for the business group you want to view.

After selecting the organization and environment group, Anypoint Visualizer displays a graph of your application network.

== View Information About All Nodes In Your Network

Use the options in the *Metric* card to select the metric and the time window that you want to show for all the nodes in your application network.
In the *Metrics* section, you can select one of the following metrics:

* *Inbound connections*
* *Errors count*
* *avg. response time*
* *avg. throughput*
* *avg. CPU consumption*
* *avg. memory utilization*

In the *Time Range* section, you can select the time window used to calculate the average values of the selected metric.

To avoid long numbers, Anypoint Visualizer uses unit prefixes to simplify your view. For example:

|===
| Avg throughput | 66.7m TPM | 66.7 milli transactions per minute | 0.0667 TPM
|===
https://en.wikipedia.org/wiki/Metric_prefix[Here is a quick review of metric prefixes], but note that, in Anypoint Visualizer, *u* represents micro, rather than *μ*.

== View Information About a Node in Your Network

When you select a node within the graph, the node and its dependency stack are highlighted and all unconnected nodes are unavailable. Anypoint Visualizer displays information about the node in a card. This card is divided into the following tabs:

The *Details* tab contains:

* *Details*: Provides information about the node.
* *Customization*: Provides information about the layer to which the node is assigned and the tags assigned to the node. You can edit the node's display name or change the layer and tags from this section.

The *Monitoring* tab contains:

* *Metrics summary*: Provides monitoring metrics for the selected node, including Errors count, avg. response time, avg. throughput, avg. CPU consumption, and avg. memory utilization.
* *Metrics chart*: Shows the time-series chart of the selected metric in the *Metric* card.


You can search for a node (service) in the *Search services* text field. Services containing your search in any part of their name are highlighted, while others fade.

== View Information About a Connection in Your Network

When you select a connection within the graph, Anypoint Visualizer displays basic information about the connection in a card.
In the card, you can edit the display name, which adds a name to the edge on the canvas.

[NOTE]
Edges displayed between services are active, meaning that they appear only if there has been traffic in the past seven days. Nonactive edges do not appear on the canvas.


[[export-view]]
== Export Your Network View

You can export the view of your network showing on your canvas to a PNG file.

* If you customized your view with filters, the customized network topology is exported.
* If you selected metrics or durations, these settings are reflected in the export.

To export a view of your network as a PNG, click the *Export as Image* button next to the zoom controls in the bottom right.

== See Also

* xref:layers.adoc[Use Layers in Anypoint Visualizer]
* xref:use-tags-in-visualizer.adoc[Use Tags in Anypoint Visualizer]
