= Visualizer Application Network
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Use Anypoint Visualizer to view a graph of your application network.

Anypoint Visualizer automatically generates the topology of the application.

To maximize visualization readability, consumer nodes (nodes that have only outbound connections) are shown at the top. Backend systems (nodes that have only inbound connections) are shown at the bottom.

When the `ClientId` category is detected for a consumer node, the nodes are grouped by `ClientId`; otherwise, they are grouped under the *External Traffic* node.
The target specified by `application/API/proxy` must have the `ClientId` enforcement policy to detect the `ClientId` value.
For usability purposes, client app names replace `ClientIds` values in the canvas.
All client apps that call the same Mule app are grouped into a single client app group node.
The number of client apps in the group is specified in the display name.

When viewing or modifying a graph, Anypoint Visualizer provides the following functionality:

* Zoom control: Use the zoom in, zoom out, and zoom fit buttons on the bottom right corner of the canvas to control the zoom. You can also use scroll to zoom in and out.
* Pan the visualization: Click and drag on the canvas to pan the visualization.

== View an Application Network in an Organization

. From Management Center, select *Visualizer*.
+
If Visualizer is not available, contact your system administrator to ensure that you have the correct permissions to access the application.

. In the environment filters in the *View* card, select an environment.
+
Anypoint Visualizer displays only the environments you have permissions to view.

. Click the check box for the business group you want to view.

After selecting the organization and environment group, Anypoint Visualizer displays a graph of your application network.

== View Information About All Services in Your Network

Use the options in the *Metric* card to select the metric that you want to show for all the nodes in your application network.
In the *Metrics* section, you can select one of the following metrics:

* *Inbound connections*
* *Avg response time*
* *Avg throughput*
* *Failures*
* *Avg CPU utilization*
* *Avg memory utilization*

For Avg response time, Avg throughput, and Failures, you can select *Inbound* or *Outbound* metrics.
If you select inbound, the value that appears on the application is the weighted average of that particular metric for all inbound connections to that node.
If you select outbound, the value is the weighted average of that metric for all outbound connections.

In the *Time Range* section, you can select the time window used to calculate the average values of the selected metric.

To avoid long numbers, Anypoint Visualizer uses unit prefixes to simplify your view. For example:

|===
| Avg throughput | 66.7m TPM | 66.7 milli transactions per minute | 0.0667 TPM
|===
https://en.wikipedia.org/wiki/Metric_prefix[Here is a quick review of metric prefixes], but note that, in Anypoint Visualizer, *u* represents micro, rather than *μ*.

Metrics are also available for connections, or _edges_, in your network. When you select average response time or average throughput, metrics also appear on applicable connections. 

== View Information About a Service in Your Network

When you select a node within the graph, the node and its dependency stack are highlighted and all unconnected nodes are unavailable.
Anypoint Visualizer displays information about the node in a card. This card is divided into the following tabs:

The *Details* tab contains:

* *Details*: Provides information about the node.
* *Customization*: Provides information about the layer to which the node is assigned and the tags assigned to the node. You can edit the node's display name or change the layer and tags from this section.

The *Monitoring* tab contains:

* *Metrics summary*
Provides monitoring metrics for the selected node, including average response time, average throughput, failures, average CPU utilization, and average memory utilization. This shows either inbound or outbound values for Avg response time, Avg throughput, and Failures, depending on what you’ve selected in the *Metric* card.
* *Metrics chart*: Shows the time-series chart of the selected metric in the *Metric* card.

When you select a node, you can click *Select dependents and dependencies*, which selects all nodes related to the service you selected.
If a single node is selected and does not have any dependents or dependencies, this option is hidden.

You can hide nodes through what you select in the canvas.

* To hide a single node, select it, and then click *Hide selected service*.
* To hide multiple nodes, multiselect them, and then click *Hide selected services*.
* To hide all of the services other than the selected nodes, you can click *Hide other services*. If you want to hide everything that is not related to a given dependency stack, select a node and then click *Select dependents and dependencies*, which selects all nodes related to the service which you selected. Then, click *Hide other services*.

You can search for a node (service) in the *Search services* text field. Services containing your search in any part of their name are highlighted, while others fade.

== View Information About a Connection in Your Network

If the selected metric is compatible, the canvas also displays metrics on the connections. When you select a connection within the graph, Anypoint Visualizer displays the edge’s metrics details in a card.
For more information about which connections support this feature, see xref:connection-metrics-compatibility.adoc[Supported Connection-Level Metrics].

[NOTE]
Edges displayed between services are active, meaning that they appear only if there has been traffic in the past seven days. Nonactive edges do not appear on the canvas.


[[export-view]]
== Export Your Network View

You can export the view of your network showing on your canvas to a PNG file.

* If you customized your view with filters, the customized network topology is exported.
* If you selected metrics or durations, these settings are reflected in the export.

To export a view of your network as a PNG, click the *Export as Image* button next to the zoom controls in the bottom right.

== See Also

* xref:layers.adoc[Use Layers in Anypoint Visualizer]
* xref:use-tags-in-visualizer.adoc[Use Tags in Anypoint Visualizer]
